# Generated by Django 3.1.2 on 2020-10-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_component', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableticket',
            old_name='count',
            new_name='amount_of_tickets',
        ),
    ]
